# Generated by Django 3.0.8 on 2020-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name slug'),
        ),
    ]
