# Generated by Django 3.0.8 on 2020-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200717_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=250, verbose_name='Video'),
        ),
    ]
